### ISSUE TITLE
Suggestion: add an option parser

### ISSUE THREAD

**Issue by tanguilp** [Qqwy/elixir_confy#5]
An option is a 2-tuple whose first element is an atom, and the second an arbitrary term.

It would be useful for:
- keywords (`{:list, :option}`)
- `{module, opts}` tuples

**Comment by Qqwy** [comment]
Great idea!

A PR is very much welcome. :blush:

**Comment by tanguilp** [comment]
https://github.com/Qqwy/elixir-specify/pull/16
