### ISSUE TITLE
Suggestion: list of parsers

### ISSUE THREAD

**Issue by tanguilp** [Qqwy/elixir_confy#9]
Would it make sense to allow setting a list of parses (in addition to the current behaviour, with 1 parser set)? Is that in the spirit of the library?

My use case is for options like `:from` from https://hexdocs.pm/plug/Plug.Static.html for instance. It can be a string, a tuple or an atom.

In my code I sometime have options who can be either a string value or the atom `:auto`.

**Comment by Qqwy** [comment]
Having a higher-level `one_of([list, of, parsers])` parser indeed might be a good idea. :+1:

**Comment by tanguilp** [comment]
Will give it a try :)
